name: CI/CD Pipeline

on:
  pull_request:
    branches:
      - master
      
  push:
    branches:
      - master

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read  # This is required for actions/checkout

jobs:
  quarkus-api:
    runs-on: ubuntu-latest
    outputs:
      result: ${{ steps.check.outputs.result }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Set up Maven
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build Quarkus Docker image
        run: |
          cd Quarkus
          chmod +x mvnw
          npm run docker-build  #docker build -t quarkus-api .
      
      - name: Configure AWS credentials
        if: github.event_name == 'push'
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::637423234931:role/AWS-Permisos
          aws-region: us-east-1

      - name: Login to Amazon ECR
        if: github.event_name == 'push'
        run: |
          aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 637423234931.dkr.ecr.us-east-1.amazonaws.com
      
      - name: Push Quarkus Docker image to ECR
        if: github.event_name == 'push'
        run: |
          docker tag quarkus-api:latest 637423234931.dkr.ecr.us-east-1.amazonaws.com/quarkus-api:latest
          docker push 637423234931.dkr.ecr.us-east-1.amazonaws.com/quarkus-api:latest       

      - name: Update ECS service for Quarkus API
        id: check  
        if: github.event_name == 'push'
        run: |
          aws ecs update-service --cluster quarkus-api-cluster --service quarkus-api-service2 --force-new-deployment --region us-east-1

  vertx-api:
    runs-on: ubuntu-latest
    outputs:
      result: ${{ steps.check.outputs.result }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Build Vert.x Docker image
        run: |
          cd Vertex
          npm run docker-build  # docker build -t vertx-api .

      - name: Configure AWS credentials
        if: github.event_name == 'push'
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::637423234931:role/AWS-Permisos
          aws-region: us-east-1

      - name: Login to Amazon ECR
        if: github.event_name == 'push'
        run: |
           aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 637423234931.dkr.ecr.us-east-1.amazonaws.com

      - name: Push Vert.x Docker image to ECR
        if: github.event_name == 'push'
        run: |
          docker tag vertx-api:latest 637423234931.dkr.ecr.us-east-1.amazonaws.com/vertx-api:latest
          docker push 637423234931.dkr.ecr.us-east-1.amazonaws.com/vertx-api:latest
          
      - name: Update ECS service for Vert.x API
        id: check
        if: github.event_name == 'push'
        run: |
          aws ecs update-service --cluster vertx-api-cluster --service vertx-api-service2 --force-new-deployment --region us-east-1 

  nativescrip-app:
    runs-on: ubuntu-latest
    steps:
    # 1. Checkout del repositorio
    - name: Checkout repository
      uses: actions/checkout@v2

    # 2. Configurar Node.js
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    # 3. Configurar Java
    - name: Setup Java
      uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: '17'

    # 4. Cachear dependencias de npm para acelerar la instalación
    - name: Cache npm dependencies
      uses: actions/cache@v3
      with:
        path: |
          ~/.npm
          nativescript/node_modules
        key: ${{ runner.os }}-npm-cache-${{ hashFiles('nativescript/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-npm-cache-

    # 5. Instalar dependencias de NativeScript
    - name: Install dependencies
      run: |
        npm install -g nativescript
        cd NativeScript
        npm install

    # 6. Configurar SDK de Android (API level y build tools)
    - name: Setup Android SDK
      uses: android-actions/setup-android@v2
      with:
        api-levels: '30'
        build-tools: '30.0.3'

    # 7. Cachear el SDK de Android para evitar descargas repetidas
    - name: Cache Android SDK
      uses: actions/cache@v3
      with:
        path: ${{ env.ANDROID_SDK_ROOT }}
        key: ${{ runner.os }}-android-sdk
        restore-keys: |
          ${{ runner.os }}-android-sdk

    # 8. Crear y lanzar el emulador Android
    - name: Create and start Android emulator
      run: |
        echo "Creating Android emulator..."
        avdmanager create avd -n test -k "system-images;android-30;google_apis;x86_64" --force
        emulator -avd test -no-audio -no-boot-anim -accel auto -gpu swiftshader_indirect &
      env:
        ANDROID_SDK_ROOT: ${{ env.ANDROID_SDK_ROOT }}

    # 9. Esperar a que el emulador esté listo
    - name: Wait for emulator to start
      run: adb wait-for-device
      env:
        ANDROID_SDK_ROOT: ${{ env.ANDROID_SDK_ROOT }}

    # 10. Ejecutar el build y probar la app en el emulador
    - name: Build and run NativeScript app on Android emulator
      run: |
        cd NativeScript
        ns build android --release
        adb install ./platforms/android/app/build/outputs/apk/debug/app-debug.apk
        adb shell monkey -p org.nativescript.app -c android.intent.category.LAUNCHER 1
      env:
        ANDROID_SDK_ROOT: ${{ env.ANDROID_SDK_ROOT }}
       
        
  nativescrip-app-request:
    runs-on: ubuntu-latest
    needs: [quarkus-api, vertx-api, nativescrip-app] 
    if: github.event_name == 'push' 
    env:
      QuarkusUrl: "http://main-829069404.us-east-1.elb.amazonaws.com"
      VertxUrl: "http://main-829069404.us-east-1.elb.amazonaws.com/vertx/"
    steps:   
      - name: Checkout repository
        uses: actions/checkout@v2   

      - name: Validate connection to Quarkus API
        run: |
          response=$(curl --write-out "%{http_code}" --silent --output /dev/null ${QuarkusUrl}/hello)
          if [ "$response" != "200" ]; then
            echo "Quarkus API not reachable. HTTP Status: $response"
            exit 1
          else
            echo "Quarkus API is reachable"
          fi

      - name: Validate connection to Vert.x API
        run: |
          response=$(curl --write-out "%{http_code}" --silent --output /dev/null ${VertxUrl}/hello)
          if [ "$response" != "200" ]; then
            echo "Vert.x API not reachable. HTTP Status: $response"
            exit 1
          else
            echo "Vert.x API is reachable"
          fi
     


