name: CI/CD Pipeline

on:
  pull_request:
    branches:
      - master  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js (si es una app Node.js)
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm test

    - name: Build Docker image
      run: docker build -t myapp .

    - name: Simulate deployment
      if: github.event.pull_request.merged == true  # Desplegar solo si el PR ha sido mergeado
      run: |
        echo "Simulating deployment..."
